services:
  cie-verona:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      POLL_INTERVAL: 1m
    volumes:
      - cie-data:/data

  sendtest:
    build:
      context: .
      dockerfile: cmd/sendtest/Dockerfile
    env_file: .env
    volumes:
      - cie-data:/data
    profiles:
      - tools

volumes:
  cie-data:
